const API='/api', $=s=>document.querySelector(s);
let selectedFile=null, inputMode='media', latestPlans=[], currentAnalysis=null;
const toast=(msg,bad=false)=>{const t=$('#toast');t.textContent=msg;t.className=`toast show ${bad?'bad':''}`;setTimeout(()=>t.className='toast',3200)};
async function api(path,options={}){const r=await fetch(API+path,options);if(!r.ok){let m=`请求失败 (${r.status})`;try{m=(await r.json()).detail||m}catch{}if([401,402,403,429].includes(r.status)||/余额|额度|quota|rate/i.test(m))m='AI 服务额度不足或请求受限，请检查余额后重试。';throw new Error(m)}return r.json()}
function openConfig(){ $('#configModal').classList.remove('hidden'); $('#arkApiKey').focus() }
function closeConfig(){ $('#configModal').classList.add('hidden') }
async function checkApi(){try{const c=await api('/config');$('#apiStatus').innerHTML=`<b></b> ${c.ark_configured?'AI 服务已连接':'配置 AI 服务'}`;$('#apiStatus').classList.toggle('offline',!c.ark_configured);if(!c.ark_configured)openConfig()}catch{$('#apiStatus').innerHTML='<b></b> 后端服务未连接';$('#apiStatus').classList.add('offline')}}
function updateReady(){const ready=inputMode==='media'?!!selectedFile:$('#productDescription').value.trim().length>=10;$('#generateBtn').disabled=!ready}
document.querySelectorAll('.input-tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.input-tab').forEach(x=>x.classList.remove('active'));tab.classList.add('active');inputMode=tab.dataset.input;$('#mediaInputPanel').classList.toggle('hidden',inputMode!=='media');$('#textInputPanel').classList.toggle('hidden',inputMode!=='text');$('#analysisBox').classList.add('hidden');updateReady()}));
function enforceMixedCount(){if(document.querySelector('input[name="mode"]:checked').value==='both'&&Number($('#count').value)<2){$('#count').value='3';toast('A+B 两条路线至少需要 2 套，已调整为 3 套')}}
document.querySelectorAll('input[name="mode"]').forEach(r=>r.addEventListener('change',enforceMixedCount));
$('#count').addEventListener('change',enforceMixedCount);
function setFile(file){if(!file)return;if(!(file.type.startsWith('image/')||file.type.startsWith('video/')))return toast('请选择图片或视频文件',true);selectedFile=file;const url=URL.createObjectURL(file),video=file.type.startsWith('video/');$('#preview').style.display=video?'none':'block';$('#videoPreview').style.display=video?'block':'none';if(video)$('#videoPreview').src=url;else $('#preview').src=url;$('#dropHint').classList.add('hidden');$('#removeFile').style.display='grid';updateReady()}
$('#fileInput').addEventListener('change',e=>setFile(e.target.files[0]));$('#productDescription').addEventListener('input',updateReady);
$('#chooseFileBtn').addEventListener('click',e=>{e.preventDefault();e.stopPropagation();$('#fileInput').click()});
$('#removeFile').addEventListener('click',e=>{e.preventDefault();selectedFile=null;$('#fileInput').value='';$('#preview').style.display='none';$('#videoPreview').style.display='none';$('#videoPreview').src='';$('#dropHint').classList.remove('hidden');e.currentTarget.style.display='none';updateReady()});
['dragenter','dragover'].forEach(n=>$('#dropzone').addEventListener(n,e=>{e.preventDefault();$('#dropzone').classList.add('drag')}));['dragleave','drop'].forEach(n=>$('#dropzone').addEventListener(n,e=>{e.preventDefault();$('#dropzone').classList.remove('drag')}));$('#dropzone').addEventListener('drop',e=>setFile(e.dataTransfer.files[0]));
function renderAnalysis(a){currentAnalysis=a;const fields=[['外观与形态',a.appearance],['核心功能',a.functions],['玩法流程',a.play],['工作原理',a.principle],['机械结构',a.mechanics],['电子模块',a.electronics],['卖点与用户',a.selling_points],['可复用特性',a.reusable_traits],['痛点与风险',a.pain_points||a.risks]];$('#analysisContent').innerHTML=fields.filter(x=>x[1]).map(x=>`<div><b>${x[0]}</b><p>${x[1]}</p></div>`).join('')+`<span class="source">来源：${a.source?.startsWith('ark')?'火山方舟 AI':'本地降级分析'} · 置信度 ${a.confidence||'—'}%</span>`;$('#analysisBox').classList.remove('hidden')}
function statusText(p){if(p<30)return'正在把灵感整理为规范产品定义…';if(p<75)return'正在沿两条路线生成产品方案…';if(p<100)return'正在绘制产品效果图…';return'全部产物已完成'}
const safe=v=>Array.isArray(v)?v.join('；'):v||'—';
function renderPlans(plans){latestPlans=plans;$('#resultGrid').innerHTML=plans.map((p,i)=>`<article class="product-card"><div class="product-image">${p.image_url?`<img src="${p.image_url}" alt="${p.name}">`:`<div class="no-image">暂无效果图<br><small>${safe(p.image_error)}</small></div>`}<span>${String(i+1).padStart(2,'0')} / ${p.type||'产品方案'}</span>${p.image_url?`<a href="${p.image_url}" target="_blank">下载图片 ↓</a>`:''}</div><div class="product-copy"><div class="card-title"><h3>${p.name}</h3><em>结构匹配 ${p.match||'—'}%</em></div><p class="appearance">${safe(p.appearance)}</p><details open><summary>改动清单</summary><p>${safe(p.changes)}</p></details><details><summary>玩法升级</summary><p>${safe(p.gameplay)}</p></details><details><summary>产品卖点</summary><p>${safe(p.selling_points)}</p></details><details class="risk"><summary>量产风险</summary><p>${safe(p.risks)}</p></details></div></article>`).join('');$('#resultSummary').textContent=`共生成 ${plans.length} 套方案；A 路线强调结构复用，B 路线强调特性迁移。`;$('#resultSection').classList.remove('hidden');$('#resultSection').scrollIntoView({behavior:'smooth'})}
$('#generateBtn').addEventListener('click',async()=>{const btn=$('#generateBtn');btn.disabled=true;$('#resultSection').classList.add('hidden');$('#progressBox').classList.remove('hidden');try{let assetId=null,analysis;if(inputMode==='media'){const form=new FormData();form.append('file',selectedFile);const upload=await api('/assets/upload',{method:'POST',body:form});assetId=upload.id;analysis=upload.analysis}else{analysis=await api('/analyze-description',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({description:$('#productDescription').value})})}renderAnalysis(analysis);$('#progressValue').textContent='25%';$('#progressBar').style.width='25%';const mode=document.querySelector('input[name="mode"]:checked').value;const job=await api('/projects/proj-001/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({direction:$('#direction').value,instruction:$('#instruction').value,count:Number($('#count').value),asset_id:assetId,mode,analysis})});while(true){await new Promise(r=>setTimeout(r,1800));const state=await api(`/jobs/${job.id}`);$('#progressValue').textContent=`${state.progress}%`;$('#progressBar').style.width=`${state.progress}%`;$('#progressText').textContent=statusText(state.progress);if(state.status==='failed')throw new Error(state.error||'生成失败');if(state.status==='completed'){renderPlans(state.plans);break}}toast('产品定义、方案和效果图已生成')}catch(e){toast(e.message,true)}finally{$('#progressBox').classList.add('hidden');btn.disabled=false}});
$('#downloadAll').addEventListener('click',async()=>{latestPlans.forEach(p=>{if(p.image_url)window.open(p.image_url,'_blank')});const r=await fetch(`${API}/projects/proj-001/export.md`),blob=await r.blob(),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='产品方案报告.md';a.click();toast('产物已开始下载')});
$('#apiStatus').addEventListener('click',openConfig);$('#closeConfig').addEventListener('click',closeConfig);$('#configModal').addEventListener('click',e=>{if(e.target.id==='configModal')closeConfig()});
$('#saveConfig').addEventListener('click',async()=>{const btn=$('#saveConfig'),key=$('#arkApiKey').value.trim();if(!key)return toast('请先填写 API Key',true);btn.disabled=true;btn.textContent='正在保存…';try{await api('/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({api_key:key,vision_model:$('#visionModel').value.trim(),llm_model:$('#llmModel').value.trim(),image_model:$('#imageModel').value.trim()})});$('#arkApiKey').value='';closeConfig();await checkApi();toast('AI 服务已连接，配置已保存到本机')}catch(e){toast(e.message,true)}finally{btn.disabled=false;btn.textContent='保存并连接'}});
checkApi();
